spring:
  application:
    name: suanfa
  data:
    redis:
      host: localhost
      password:
      database: 0
server:
  port: 9090
dubbo:
  application:
    name: demo-filter
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: multicast://224.5.6.7:1234
  provider:
    filter: loggingFilter,rpcResultMonitorFilter
  consumer:
    check: false
    filter: loggingFilter,rpcResultMonitorFilter
logging:
  level:
    org.example.suanfa.project.dubboFilter: DEBUG
    org.apache.dubbo: INFO