spring:
  redis:
    port: 6379
    database: 10
    host: localhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stress_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: he13140303042

logging:
  level:
    org:
      apache:
        commons:
          beanutils=ERROR:
server:
  port: 2000